" Disable bell noise and flash
set belloff=all

" Display Line Numbers
set number

" Enable automatic indentation
set autoindent

" Enable filetype detection:
filetype on
filetype plugin on
filetype indent on 

" Use spaces instead of tabs
set textwidth=0 tabstop=2 shiftwidth=2 softtabstop=2 expandtab

" Use tabs instead of spaces for makefiles only
autocmd FileType make set noexpandtab shiftwidth=8 softtabstop=0

" Auto complete matching characters
" https://vim.fandom.com/wiki/Automatically_append_closing_characters
inoremap {      {}<Left>
inoremap {}     {}
inoremap (      ()<Left>
inoremap ()     ()
inoremap [      []<Left>
inoremap []     []
