" Load all plugins now.
" Plugins need to be added to runtimepath before helptags can be generated.
packloadall
" Load all of the helptags now, after plugins have been loaded.
" All messages and errors will be ignored.
silent! helptags ALL

" Make sure syntax highlighting is on
syntax on

" Disable bell noise and flash
set belloff=all

" Display options
set number
set cursorline
set ruler

" Enable automatic indentation
set autoindent

" Start scrolling near screen boundaries
set so=3

" Enable filetype detection:
filetype on
filetype plugin on
filetype indent on 

" Use spaces instead of tabs
set textwidth=0 tabstop=2 shiftwidth=2 softtabstop=2 expandtab

" Use tabs instead of spaces for makefiles only
autocmd FileType make set noexpandtab shiftwidth=8 softtabstop=0

" Collect vim files in .cache and use undo files as well.
set backupdir=~/.config/vim/cache/backup/    " where to put backup files.
set directory=~/.config/vim/cache/swap/      " where to put swap files.
set undodir=~/.config/vim/cache/undo/      " where to put undo files.
set undofile
