#!/bin/bash

# Add bin directory
export PATH="$HOME/.bin:$PATH"

# shellcheck disable=SC1091  # external file, not present at lint time
[[ -r "/opt/homebrew/etc/profile.d/bash_completion.sh" ]] && . "/opt/homebrew/etc/profile.d/bash_completion.sh"
